-- Tabla Envio
create table ENVIO
(
  ID_FACTURA VARCHAR(10) primary key,
  DIRECCION_DESTINATARIO VARCHAR(50) not null,
  CI_DESTINATARIO VARCHAR(10) not null,
  Telefono_DESTINATARIO VARCHAR(10) not null,
  ESTADO BIT not null,
  FECHA_FINALIZACION DATE,
  CONSTRAINT fk_RUC FOREIGN KEY (RUC_REMITENTE) REFERENCES CLIENTE (RUC) -- 
);

-- Tabla Chofer_Envio
create table CHOFER_ENVIO
(
  ID VARCHAR(20) primary key,
  CI_CHOFER VARCHAR(10) not null,
  ID_ENVIO VARCHAR(10) not null,
  CONSTRAINT fk_RUC FOREIGN KEY (RUC_REMITENTE) REFERENCES CLIENTE (RUC) --
);

-- Tabla Factura
create table FACTURA
(
  ID VARCHAR(10) primary key,
  FECHA DATE not null,
  RUC_CLIENTE  VARCHAR(10) not null,
  DIRECCION_CLIENTE VARCHAR(50) not null,
  TELEFONO_CLIENTE VARCHAR(10) not null,
  DETALLES VARCHAR(50) not null,
  COSTO FLOAT not null,
  CONSTRAINT fk_RUC FOREIGN KEY (RUC_CLIENTE) REFERENCES CLIENTE (RUC),
  CONSTRAINT fk_ID_ENVIO FOREIGN KEY (ID_ENVIO) REFERENCES ENVIO (ID_ENVIO)
);

-- Tabla Informe
create table Informe
(
  ID VARCHAR(20) primary key,
  CI_CHOFER VARCHAR(10) not null,
  MATRICULA_VEHICULO  VARCHAR(10) not null,
  COMBUSTIBLE FLOAT not null, --Son dolares
  KILOMETRAJE FLOAT not null,
  FECHA_GESTION DATE not null,
  CONSTRAINT fk_MATRICULA_I FOREIGN KEY (MATRICULA_VEHICULO) REFERENCES VEHICULO (MATRICULA),
  CONSTRAINT fk_CI_I FOREIGN KEY (CI_CHOFER) REFERENCES EMPLEADOS (CI)
  ON UPDATE cascade
  ON DELETE cascade
);


